import { serve } from 'https://deno.land/std@0.208.0/http/server.ts';
import { handleCors, jsonError, jsonOk } from '../_shared/cors.ts';
import { getSupabaseAdmin, verifyAuth } from '../_shared/supabase-admin.ts';

// Initiates batch payout for selected users.
// Selects 'accrued' earnings, groups by user, creates payments.

serve(async (req) => {
  const corsResp = handleCors(req);
  if (corsResp) return corsResp;

  try {
    const { userId } = await verifyAuth(req);
    const supabase = getSupabaseAdmin();

    // Verify caller has finance/admin permissions
    const { data: adminUser, error: adminErr } = await supabase
      .from('admin_users')
      .select('id, role')
      .eq('id', userId)
      .eq('active', true)
      .single();

    if (adminErr || !adminUser) {
      return jsonError(403, 'Only finance/admin roles can initiate payouts');
    }

    const allowedRoles = ['super_admin', 'admin', 'finance'];
    if (!allowedRoles.includes(adminUser.role)) {
      return jsonError(403, 'Insufficient permissions to initiate payouts');
    }

    const body = await req.json();
    const { user_ids } = body;

    if (!user_ids || !Array.isArray(user_ids) || user_ids.length === 0) {
      return jsonError(400, 'user_ids array is required and must not be empty');
    }

    const results: Array<{ user_id: string; payment_code: string; amount: number; status: string }> = [];

    for (const uid of user_ids) {
      // Fetch all accrued earnings for this user
      const { data: earnings, error: earnErr } = await supabase
        .from('user_earnings')
        .select('id, amount')
        .eq('user_id', uid)
        .eq('status', 'accrued');

      if (earnErr || !earnings || earnings.length === 0) {
        results.push({ user_id: uid, payment_code: '', amount: 0, status: 'skipped_no_accrued' });
        continue;
      }

      const totalAmount = earnings.reduce((sum, e) => sum + Number(e.amount), 0);

      if (totalAmount <= 0) {
        results.push({ user_id: uid, payment_code: '', amount: 0, status: 'skipped_zero_amount' });
        continue;
      }

      // Fetch user's primary bank account for payout routing
      const { data: bankAccount } = await supabase
        .from('bank_accounts')
        .select('id, upi_id, account_number_last4, ifsc')
        .eq('user_id', uid)
        .eq('is_primary', true)
        .single();

      if (!bankAccount) {
        results.push({ user_id: uid, payment_code: '', amount: totalAmount, status: 'skipped_no_bank' });
        continue;
      }

      // Create payment record (payment_code generated by trigger)
      const { data: payment, error: payErr } = await supabase
        .from('payments')
        .insert({
          user_id: uid,
          amount: totalAmount,
          payment_method: bankAccount.upi_id ? 'upi' : 'bank_transfer',
          status: 'initiated',
          initiated_by: adminUser.id,
        })
        .select('id, payment_code')
        .single();

      if (payErr || !payment) {
        results.push({ user_id: uid, payment_code: '', amount: totalAmount, status: 'error_creating_payment' });
        continue;
      }

      // Link earnings to this payment
      const paymentEarnings = earnings.map((e) => ({
        payment_id: payment.id,
        earning_id: e.id,
      }));

      const { error: linkErr } = await supabase
        .from('payment_earnings')
        .insert(paymentEarnings);

      if (linkErr) {
        results.push({ user_id: uid, payment_code: payment.payment_code, amount: totalAmount, status: 'error_linking_earnings' });
        continue;
      }

      // Update earnings status to 'processing'
      const earningIds = earnings.map((e) => e.id);
      await supabase
        .from('user_earnings')
        .update({ status: 'processing' })
        .in('id', earningIds);

      // In production, call Razorpay/Cashfree Payouts API here.
      // For now, we mark as 'initiated' and let the webhook update status.
      // const payoutResponse = await callPayoutGateway(bankAccount, totalAmount);

      results.push({
        user_id: uid,
        payment_code: payment.payment_code,
        amount: totalAmount,
        status: 'initiated',
      });

      // Audit log
      await supabase.from('audit_log').insert({
        actor_id: userId,
        actor_type: 'admin',
        action: 'payout_initiated',
        entity_table: 'payments',
        entity_id: payment.id,
        after: JSON.stringify({
          user_id: uid,
          amount: totalAmount,
          earning_count: earnings.length,
        }),
      });

      // Notification to user
      await supabase.from('notifications').insert({
        user_id: uid,
        type: 'payout_initiated',
        title: 'Payout Initiated',
        body: `A payout of ₹${totalAmount.toFixed(2)} has been initiated for your account.`,
      });
    }

    return jsonOk({ results });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return jsonError(500, message);
  }
});
