import { serve } from 'https://deno.land/std@0.208.0/http/server.ts';
import { handleCors, jsonError, jsonOk } from '../_shared/cors.ts';
import { getSupabaseAdmin } from '../_shared/supabase-admin.ts';

// Verifies OTP and signs in/up the user via Supabase Auth.

serve(async (req) => {
  const corsResp = handleCors(req);
  if (corsResp) return corsResp;

  try {
    const body = await req.json();
    const { phone, otp, full_name, email } = body;

    if (!phone || !otp) {
      return jsonError(400, 'phone and otp are required');
    }

    if (!/^\d{10}$/.test(phone)) {
      return jsonError(400, 'Valid 10-digit phone number required');
    }

    if (!/^\d{6}$/.test(otp)) {
      return jsonError(400, 'OTP must be 6 digits');
    }

    const supabase = getSupabaseAdmin();

    // Verify OTP against stored hash
    const hashedOTP = await hashOTP(otp);
    const { data: otpRecord, error: otpErr } = await supabase
      .from('otp_codes')
      .select('id, phone, expires_at')
      .eq('phone', phone)
      .eq('otp_code', hashedOTP)
      .gt('expires_at', new Date().toISOString())
      .order('created_at', { ascending: false })
      .limit(1)
      .single();

    if (otpErr || !otpRecord) {
      return jsonError(401, 'Invalid or expired OTP');
    }

    // Delete used OTP
    await supabase.from('otp_codes').delete().eq('id', otpRecord.id);

    // Check if user already exists
    const { data: existingUser } = await supabase
      .from('users')
      .select('id')
      .eq('mobile', phone)
      .single();

    let userId: string;

    if (existingUser) {
      // Existing user — sign in
      userId = existingUser.id;

      // Mark mobile as verified
      await supabase
        .from('users')
        .update({ mobile_verified: true })
        .eq('id', userId);

    } else {
      // New user — create account
      // First, create auth user with phone as identity
      const { data: authUser, error: authErr } = await supabase.auth.admin.createUser({
        phone: `+91${phone}`,
        phone_confirm: true,
        user_metadata: { full_name: full_name || '' },
      });

      if (authErr || !authUser) {
        return jsonError(500, `Failed to create auth user: ${authErr?.message}`);
      }

      userId = authUser.id;

      // Insert into public users table
      // user_code is auto-generated by trigger
      const { error: userErr } = await supabase.from('users').insert({
        id: userId,
        full_name: full_name || 'New User',
        mobile: phone,
        mobile_verified: true,
        email: email || null,
        status: 'pending_verification',
        overall_verification: 'not_submitted',
      });

      if (userErr) {
        return jsonError(500, `Failed to create user profile: ${userErr.message}`);
      }
    }

    // Issue a JWT via Supabase Auth sign-in
    // For phone-based auth, we use the admin API to generate a session
    const { data: session, error: sessionErr } = await supabase.auth.admin.generateLink({
      type: 'magiclink',
      phone: `+91${phone}`,
    });

    // Alternative: return the user ID and let the client use Supabase's
    // signInWithOtp / verifyOtp flow. For now, we return a success indicator
    // and the client completes auth via supabase-js.

    return jsonOk({
      success: true,
      user_id: userId,
      is_new_user: !existingUser,
      message: 'OTP verified. Use supabase.auth.signInWithOtp() on the client to complete authentication.',
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return jsonError(500, message);
  }
});

async function hashOTP(otp: string): Promise<string> {
  const encoder = new TextEncoder();
  const data = encoder.encode(otp + (Deno.env.get('OTP_SALT') || 'workflow-pay-salt'));
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map((b) => b.toString(16).padStart(2, '0')).join('');
}
